name: atmosscibot 
channels:
   - conda-forge 
dependencies:
   - python=3.5
   - beautifulsoup4
   - feedparser
   - lxml
   - matplotlib
   - numpy
   - pillow
   - requests
   - tinydb
   - wordcloud
   - pip:
       - fake_useragent
       - tweepy
       - git+https://github.com/bitly/bitly-api-python
