name: atmosscibot 
channels:
   - conda-forge 
dependencies:
   - python=3.10
   - beautifulsoup4
   - fake-useragent
   - feedparser
   - geckodriver
   - ipython
   - lxml
   - matplotlib
   - numpy
   - pillow
   - pip
   - requests
   - selenium
   - tinydb
   - tweepy=<4.0
   - wordcloud
   - pip:
       - git+https://github.com/bitly/bitly-api-python
