name: atmosscibot 
channels:
   - defaults
dependencies:
   - python=3.4
   - lxml
   - numpy
   - pillow
   - pip:
       - beautifulsoup4
       - feedparser
       - requests
       - tinydb
       - tweepy
       - wordcloud
       - git+https://github.com/bitly/bitly-api-python
